services:
  - type: web
    name: gml5
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app

crons:
  - name: keep-engine-alive
    schedule: "*/5 * * * *" # Runs every 5 minutes
    command: curl https://gml5.onrender.com/api/data
    service: gml5
